### ISSUE TITLE
Please update for sbt-web 1.5.x

### ISSUE THREAD

**Issue by PromanSEW** [platypii/sbt-typescript#5]
This plugin does not work with Play Framework 2.9.0 anymore
Please update
Here is stacktrace:
```
[info] Typescript compiling on 6 source(s)
[error] stack trace is suppressed; run 'last Web-assets / typescript' for the full output
[error] (Web-assets / typescript) java.lang.NoSuchMethodError: 'java.lang.Object com.typesafe.sbt.web.SbtWeb$.withActorRefFactory(sbt.State, java.lang.String, scala.Function1)'
ERROR a.a.ActorSystemImpl - Internal server error, sending 500 response
scala.MatchError: java.lang.NoSuchMethodError: 'java.lang.Object com.typesafe.sbt.web.SbtWeb$.withActorRefFactory(sbt.State, java.lang.String, scala.Function1)' (of class java.lang.NoSuchMethodError)
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$8(PlayReload.scala:92)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:92)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:144)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:144)
        at sbt.PlayRun$.$anonfun$playRunTask$5(PlayRun.scala:99)
        at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:493)
        at play.runsupport.Reloader$$anon$1.run(Reloader.scala:58)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
```

**Comment by platypii** [comment]
sbt-typescript version 5.3.2 published to maven central
